.TH sodamake 1 "JANUARY 2018" Soda "Simple Object Driven Automation"
.SH NAME
sodamake \-\- initializes a new Soda scripts project
.SH SYNOPSIS
.B sodamake
.I destination_directory
.I project_name
.SH DESCRIPTION
The
.I sodamake
command creates a soda project folder with the proper structure in
.I destination_directory
with the name
.I project_name.
Argument
.I destination_directory
is required.
If the folder already exists in
.I destination_directory,
the program is aborted.

.SH AUTHOR
Jason Pollman & James Pavlic
.SH "SEE ALSO"
.BR soda (1),
.BR sodabuild (1),
.BR sodareset (1)
.BR sodatrace (1)
.BR sodarun (1)
.BR sodaeditor (1)
