.TH sodaeditor 1 "JANUARY 2018" Soda "Simple Object Driven Automation"
.SH NAME
sodaeditor \-\- starts the Soda Visual Editor
.SH DESCRIPTION
The
.I sodaeditor
command starts the Soda Visual Editor on your local machine. No arguments required.

.SH AUTHOR
Jason Pollman & James Pavlic
.SH "SEE ALSO"
.BR soda (1),
.BR sodabuild (1),
.BR sodamake (1),
.BR sodareset (1)
.BR sodatrace (1)
.BR sodarun (1)
